### ISSUE TITLE
Is winner announced?

### ISSUE THREAD

**Issue by kartikmehta8** [appwrite-community/htf24-hackathon-submissions#147]

**Comment by kartikmehta8** [comment]
Hello @adityaoberai!

Is winner announced for this challenge? I didn't got any mail regarding this.

**Comment by adityaoberai** [comment]
Hi @kartikmehta8 
The winners were announced in the Appwrite Discord server and social media.

https://x.com/appwrite/status/1858867772677149007?t=q82HGVnKWnX_zpWNrVgn-w&s=19
